### ISSUE TITLE
Generators still return full CausalFrames

### ISSUE THREAD

**Issue by MaximilianFranz** [inovex/justcause#11]
replace that with an iterator over replications in the same manner as with the datasets.

**Comment by MaximilianFranz** [comment]
@FlorianWilhelm I think it would be more consistent to have the same handling for generators and datasets when it comes to the evaluation. 

Or should we keep it like that, because one can already select how many replication one wants? 

Pro Change: 
 - Same usage with the iterator of which we can sample a list of CausalFrames, one for each rep

Con Change: 
 - Number of replication can already be selected when calling the generator

I am in favour of changing it!

**Comment by FlorianWilhelm** [comment]
@MaximilianFranz I would the interfaces of datasets and generators consistent and thus would also change it accordingly.

**Comment by FlorianWilhelm** [comment]
@MaximilianFranz, is this already fixed and merged?

**Comment by MaximilianFranz** [comment]
Yes, thanks for the reminder!
