### ISSUE TITLE
Have a bibliography

### ISSUE THREAD

**Issue by FlorianWilhelm** [inovex/justcause#16]
Instead of citing each time the whole paper it would be nicer to have a bibliography and to reference it using https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html

**Comment by MaximilianFranz** [comment]
Dismissed in favour of local references! 

Pro local: 
 - Easier to find
 - Easier to implement 

Con: 
 - Duplicate references
